// src/lib/export/markdown.ts
// Génère un fichier Markdown complet à partir des artefacts d'un projet

interface ExportArtifact {
  type: string
  content: any
}

interface ExportProject {
  name: string
  description: string
  template: string | null
  createdAt: Date
  artifacts: ExportArtifact[]
}

export function generateMarkdown(project: ExportProject): string {
  const lines: string[] = []
  const date = new Date(project.createdAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  })

  // Header
  lines.push(`# ${project.name}`)
  lines.push(``)
  lines.push(`> Generated by AI Software Architect on ${date}`)
  if (project.template) lines.push(`> Template: ${project.template}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  for (const artifact of project.artifacts) {
    if (!artifact.content) continue

    switch (artifact.type) {
      case 'business_analysis':
        lines.push(...renderBusinessAnalysis(artifact.content))
        break
      case 'architecture':
        lines.push(...renderArchitecture(artifact.content))
        break
      case 'database_schema':
        lines.push(...renderDatabaseSchema(artifact.content))
        break
      case 'diagrams':
        lines.push(...renderDiagrams(artifact.content))
        break
      case 'backlog':
        lines.push(...renderBacklog(artifact.content))
        break
    }

    lines.push(``)
    lines.push(`---`)
    lines.push(``)
  }

  return lines.join('\n')
}

function renderBusinessAnalysis(c: any): string[] {
  const lines: string[] = []
  lines.push(`## Business Analysis`)
  lines.push(``)
  lines.push(c.summary)
  lines.push(``)

  lines.push(`### Actors`)
  lines.push(``)
  for (const actor of c.actors ?? []) {
    lines.push(`**${actor.name}** (${actor.role})`)
    lines.push(`${actor.description}`)
    lines.push(``)
  }

  lines.push(`### Features`)
  lines.push(``)
  lines.push(`| Feature | Priority | Actor | Description |`)
  lines.push(`|---|---|---|---|`)
  for (const f of c.features ?? []) {
    lines.push(`| ${f.name} | ${f.priority} | ${f.actor} | ${f.description} |`)
  }
  lines.push(``)

  if (c.businessRules?.length) {
    lines.push(`### Business Rules`)
    lines.push(``)
    for (const rule of c.businessRules) lines.push(`- ${rule}`)
    lines.push(``)
  }

  if (c.constraints?.length) {
    lines.push(`### Constraints`)
    lines.push(``)
    for (const constraint of c.constraints) lines.push(`- ${constraint}`)
    lines.push(``)
  }

  if (c.assumptions?.length) {
    lines.push(`### Assumptions`)
    lines.push(``)
    for (const assumption of c.assumptions) lines.push(`- ${assumption}`)
    lines.push(``)
  }

  if (c.outOfScope?.length) {
    lines.push(`### Out of Scope`)
    lines.push(``)
    for (const item of c.outOfScope) lines.push(`- ${item}`)
    lines.push(``)
  }

  return lines
}

function renderArchitecture(c: any): string[] {
  const lines: string[] = []
  lines.push(`## Architecture`)
  lines.push(``)
  lines.push(`**Style:** ${c.style}`)
  lines.push(``)
  lines.push(c.overview)
  lines.push(``)
  lines.push(`*Justification: ${c.justification}*`)
  lines.push(``)

  lines.push(`### Technology Stack`)
  lines.push(``)
  lines.push(`| Layer | Technology | Justification |`)
  lines.push(`|---|---|---|`)
  for (const s of c.stack ?? []) {
    lines.push(`| ${s.layer} | **${s.technology}** | ${s.justification} |`)
  }
  lines.push(``)

  lines.push(`### Modules`)
  lines.push(``)
  for (const m of c.modules ?? []) {
    lines.push(`**${m.name}** — ${m.responsibility}`)
    lines.push(`Technology: \`${m.technology}\``)
    if (m.dependencies?.length) lines.push(`Dependencies: ${m.dependencies.join(', ')}`)
    lines.push(``)
  }

  if (c.patterns?.length) {
    lines.push(`### Patterns`)
    lines.push(``)
    for (const p of c.patterns) {
      lines.push(`- **${p.name}**: ${p.justification}`)
    }
    lines.push(``)
  }

  if (c.risks?.length) {
    lines.push(`### Risks`)
    lines.push(``)
    lines.push(`| Severity | Risk | Mitigation |`)
    lines.push(`|---|---|---|`)
    for (const r of c.risks) {
      lines.push(`| ${r.severity} | ${r.description} | ${r.mitigation} |`)
    }
    lines.push(``)
  }

  if (c.scalabilityNotes) {
    lines.push(`### Scalability`)
    lines.push(``)
    lines.push(c.scalabilityNotes)
    lines.push(``)
  }

  return lines
}

function renderDatabaseSchema(c: any): string[] {
  const lines: string[] = []
  lines.push(`## Database Schema`)
  lines.push(``)
  lines.push(`**Engine:** ${c.engine}`)
  lines.push(``)
  lines.push(`*${c.justification}*`)
  lines.push(``)

  for (const table of c.tables ?? []) {
    lines.push(`### \`${table.name}\``)
    lines.push(``)
    lines.push(table.description)
    lines.push(``)
    lines.push(`| Column | Type | Nullable | Notes |`)
    lines.push(`|---|---|---|---|`)
    for (const col of table.columns ?? []) {
      const notes = [
        col.primaryKey ? '🔑 PK' : '',
        col.foreignKey ? `→ ${col.foreignKey.table}` : '',
        col.unique ? 'UNIQUE' : '',
        col.default ? `DEFAULT: ${col.default}` : '',
      ].filter(Boolean).join(' | ')
      lines.push(`| \`${col.name}\` | \`${col.type}\` | ${col.nullable ? 'YES' : 'NO'} | ${notes} |`)
    }
    lines.push(``)
  }

  if (c.relations?.length) {
    lines.push(`### Relations`)
    lines.push(``)
    lines.push(`| From | To | Type |`)
    lines.push(`|---|---|---|`)
    for (const r of c.relations) {
      lines.push(`| \`${r.from}\` | \`${r.to}\` | ${r.type} |`)
    }
    lines.push(``)
  }

  return lines
}

function renderDiagrams(c: any): string[] {
  const lines: string[] = []
  lines.push(`## Diagrams`)
  lines.push(``)

  if (c.c4_container) {
    lines.push(`### Container Diagram`)
    lines.push(``)
    lines.push('```mermaid')
    lines.push(c.c4_container)
    lines.push('```')
    lines.push(``)
  }

  if (c.sequence) {
    lines.push(`### Sequence Diagram`)
    lines.push(``)
    lines.push('```mermaid')
    lines.push(c.sequence)
    lines.push('```')
    lines.push(``)
  }

  if (c.erd) {
    lines.push(`### Entity Relationship Diagram`)
    lines.push(``)
    lines.push('```mermaid')
    lines.push(c.erd)
    lines.push('```')
    lines.push(``)
  }

  if (c.deployment) {
    lines.push(`### Deployment Diagram`)
    lines.push(``)
    lines.push('```mermaid')
    lines.push(c.deployment)
    lines.push('```')
    lines.push(``)
  }

  return lines
}

function renderBacklog(c: any): string[] {
  const lines: string[] = []
  lines.push(`## Development Backlog`)
  lines.push(``)
  lines.push(`**Total story points:** ${c.totalStoryPoints}`)
  lines.push(`**Estimated sprints:** ${c.estimatedSprintsCount}`)
  lines.push(`**MVP stories:** ${c.mvpStories?.join(', ')}`)
  lines.push(``)

  lines.push(`### Epics`)
  lines.push(``)
  lines.push(`| ID | Epic | Priority | Description |`)
  lines.push(`|---|---|---|---|`)
  for (const epic of c.epics ?? []) {
    lines.push(`| ${epic.id} | **${epic.name}** | ${epic.priority} | ${epic.description} |`)
  }
  lines.push(``)

  lines.push(`### User Stories`)
  lines.push(``)
  for (const story of c.stories ?? []) {
    const mvp = c.mvpStories?.includes(story.id) ? ' 🎯 MVP' : ''
    lines.push(`#### ${story.id} — ${story.title}${mvp}`)
    lines.push(``)
    lines.push(`**As a** ${story.asA}, **I want** ${story.iWant}, **so that** ${story.soThat}.`)
    lines.push(``)
    lines.push(`| Priority | Story Points | Epic |`)
    lines.push(`|---|---|---|`)
    lines.push(`| ${story.priority} | ${story.storyPoints} | ${story.epicId} |`)
    lines.push(``)
    lines.push(`**Acceptance criteria:**`)
    lines.push(``)
    for (const ac of story.acceptanceCriteria ?? []) {
      lines.push(`- ${ac}`)
    }
    if (story.technicalNotes) {
      lines.push(``)
      lines.push(`*Technical notes: ${story.technicalNotes}*`)
    }
    lines.push(``)
  }

  return lines
}